language: minimal
dist: xenial
services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/plicease/cip/main/bin/travis-bootstrap | bash
  - cip before-install

install:
  - cip diag
  - cip install

script:
  - cip script

jobs:
  include:
    - env: CIP_TAG=5.33
    - env: CIP_TAG=5.32           CIP_ENV=EXTRA_CI=1
    - env: CIP_TAG=5.32-alpine3.9 CIP_ENV=EXTRA_CI=1
    - env: CIP_TAG=5.32-centos7   CIP_ENV=EXTRA_CI=1
    - env: CIP_TAG=5.32-fedora29  CIP_ENV=EXTRA_CI=1

branches:
  only:
    - main

cache:
  directories:
    - "$HOME/.cip"
